export { FacebookIcon } from './FacebookIcon'
export { InstagramIcon } from './InstagramIcon'
export { TiktokIcon } from './TiktokIcon'
export { TwitterIcon } from './TwitterIcon'
export { GoogleIcon } from './GoogleIcon'
export { FacebookIconColor } from './FacebookIconColor'